import { IdempotencyStore, MemoryIdempotencyStore } from './idempotency.js';
import * as crypto from 'crypto';

export * from './idempotency.js';

export interface WebhookEvent<T = unknown> {
  id: string;
  type: string;
  data: {
    object: T;
  };
  created: number;
}

export type WebhookHandler<T = unknown> = (event: WebhookEvent<T>) => Promise<Record<string, unknown> | void>;

export interface StripeWebhookGuardConfig {
  /**
   * Secret key for verifying Stripe webhook cryptographic signatures.
   */
  webhookSecret?: string;
  /**
   * Storage backend for idempotency and duplicate lock management.
   */
  store?: IdempotencyStore;
  /**
   * Allowed clock drift tolerance in seconds (default: 300s / 5 mins).
   */
  toleranceSeconds?: number;
}

export interface WebhookProcessingResult {
  success: boolean;
  status: 'PROCESSED' | 'DUPLICATE_IGNORED' | 'SIGNATURE_FAILED' | 'HANDLER_ERROR';
  eventId?: string;
  eventType?: string;
  message: string;
  details?: unknown;
}

/**
 * Enterprise Stripe Webhook Guard: Handles cryptographic validation, strict database idempotency,
 * duplicate suppression, and safe error propagation for Node.js / TypeScript backends.
 */
export class StripeWebhookGuard {
  private webhookSecret?: string;
  private store: IdempotencyStore;
  private toleranceSeconds: number;
  private handlers = new Map<string, WebhookHandler[]>();
  private defaultHandler?: WebhookHandler;

  constructor(config: StripeWebhookGuardConfig = {}) {
    this.webhookSecret = config.webhookSecret;
    this.store = config.store || new MemoryIdempotencyStore();
    this.toleranceSeconds = config.toleranceSeconds || 300;
  }

  /**
   * Registers an asynchronous handler function for a specific Stripe event type (e.g. 'checkout.session.completed').
   */
  on<T = unknown>(eventType: string, handler: WebhookHandler<T>): this {
    const existing = this.handlers.get(eventType) || [];
    existing.push(handler as WebhookHandler);
    this.handlers.set(eventType, existing);
    return this;
  }

  /**
   * Fallback handler invoked for all unhandled event types.
   */
  onAny(handler: WebhookHandler): this {
    this.defaultHandler = handler;
    return this;
  }

  /**
   * Verifies the cryptographic HMAC SHA256 signature generated by Stripe.
   */
  verifySignature(rawBody: string | Buffer, signatureHeader: string, secret?: string): boolean {
    const signingSecret = secret || this.webhookSecret;
    if (!signingSecret) {
      // If no secret provided, skip verification (development mode only)
      return true;
    }

    try {
      const parts = signatureHeader.split(',');
      let timestamp = 0;
      const signatures: string[] = [];

      for (const part of parts) {
        const [k, v] = part.trim().split('=');
        if (k === 't') timestamp = parseInt(v, 10);
        if (k === 'v1') signatures.push(v);
      }

      if (!timestamp || signatures.length === 0) {
        return false;
      }

      // Check timestamp freshness against replay attacks
      const now = Math.floor(Date.now() / 1000);
      if (Math.abs(now - timestamp) > this.toleranceSeconds) {
        return false;
      }

      // Compute expected HMAC SHA256 signature
      const payload = `${timestamp}.${typeof rawBody === 'string' ? rawBody : rawBody.toString('utf8')}`;
      const expectedSignature = crypto
        .createHmac('sha256', signingSecret)
        .update(payload, 'utf8')
        .digest('hex');

      return signatures.some(sig => crypto.timingSafeEqual(Buffer.from(sig, 'hex'), Buffer.from(expectedSignature, 'hex')));
    } catch {
      return false;
    }
  }

  /**
   * Ingests and processes a raw webhook event with zero duplicate execution risk.
   */
  async processEvent(
    rawBody: string | Buffer,
    signatureHeader?: string
  ): Promise<WebhookProcessingResult> {
    // 1. Verify Signature
    if (this.webhookSecret && signatureHeader) {
      const isValid = this.verifySignature(rawBody, signatureHeader);
      if (!isValid) {
        return {
          success: false,
          status: 'SIGNATURE_FAILED',
          message: 'Invalid Stripe signature or timestamp drift exceeded.'
        };
      }
    }

    // 2. Parse Event JSON
    let event: WebhookEvent;
    try {
      const bodyStr = typeof rawBody === 'string' ? rawBody : rawBody.toString('utf8');
      event = JSON.parse(bodyStr);
    } catch (err) {
      return {
        success: false,
        status: 'HANDLER_ERROR',
        message: 'Failed to parse webhook JSON payload.',
        details: String(err)
      };
    }

    if (!event.id || !event.type) {
      return {
        success: false,
        status: 'HANDLER_ERROR',
        message: 'Missing event id or type in payload.'
      };
    }

    // 3. Acquire Idempotency Lock
    const isNew = await this.store.acquireLock(event.id, 600);
    if (!isNew) {
      return {
        success: true,
        status: 'DUPLICATE_IGNORED',
        eventId: event.id,
        eventType: event.type,
        message: `Duplicate event ${event.id} suppressed. Lock already held.`
      };
    }

    // 4. Dispatch to Handlers
    try {
      const targetHandlers = this.handlers.get(event.type) || [];
      if (targetHandlers.length === 0 && this.defaultHandler) {
        targetHandlers.push(this.defaultHandler);
      }

      for (const handler of targetHandlers) {
        await handler(event);
      }

      // 5. Mark Completed
      await this.store.markCompleted(event.id, { processedAt: new Date().toISOString() });

      return {
        success: true,
        status: 'PROCESSED',
        eventId: event.id,
        eventType: event.type,
        message: `Successfully processed event ${event.id} (${event.type}).`
      };
    } catch (err) {
      await this.store.markFailed(event.id, String(err));
      return {
        success: false,
        status: 'HANDLER_ERROR',
        eventId: event.id,
        eventType: event.type,
        message: `Error executing handler for event ${event.id}: ${String(err)}`,
        details: err
      };
    }
  }
}
